### ISSUE TITLE
Reduce the size of social network footer to gain more screen space

### ISSUE THREAD

**Issue by walidshaari** [play-with-docker/play-with-docker.github.io#109]
In orchestration labs, one needs as much screen space as he/she can get. the current PWD footer seems to be quite wide, if there is either a toggle or reduce its size not to stand in the way would be better.  the file responsible could be play-with-docker.github.io/_includes/footer.html

**Comment by marcosnils** [comment]
@walidshaari that's correct. I guess a first approach would be to reduce the size of these icons https://github.com/play-with-docker/play-with-docker.github.io/blob/master/_includes/footer.html#L17-L21. 

Would you like to give it a try?. Deploying the site locally is quite easy, instructions are in the readme.

**Comment by walidshaari** [comment]
sure, will give it a try

**Comment by ibnesayeed** [comment]
This is taking a lot of screen real estate and persists there all the time. This can perhaps be moved to the footer of the scrollable post, use smaller icons, and do not use text and logo both.

**Comment by ibnesayeed** [comment]
#157 should take care of this.
