### ISSUE TITLE
PWD for Multi-stage builds does not work

### ISSUE THREAD

**Issue by klausmoser** [play-with-docker/play-with-docker.github.io#118]
The PWD classroom for Multi-stage builds (https://training.play-with-docker.com/multi-stage/) does not work in any of my Browsers (FF, Chrome, Edge,...). After the successful login nothing happens. 
In the debug console there is an issue with a POST request via XHR. The server returns with an status 405 for this request.

**Comment by marcosnils** [comment]
Hey @klausmoser thx for reporting this issue. Just found the problem and submit a commit to fix it. Lab should be up soon.
