### ISSUE TITLE
Cannot copy selected text from the terminal

### ISSUE THREAD

**Issue by dannyhajj** [play-with-docker/play-with-docker.github.io#121]
I am using Firefox 60.0b5 (64-bit) on Ubuntu 17.10.

I am not able to copy selected text in the terminal when using Firefox (However, I can paste text from the clipboard).
Using <kbd>Ctrl</kbd>+<kbd>C</kbd> is interpreted by the terminal as a SIGINT. Also, trying to use the copy option from the context menu is not possible as the option isn't available.

These are the available options in Firefox's context menu when I have text selected in the terminal:
![Firefox context menu](https://user-images.githubusercontent.com/530409/37772742-44a082c4-2de4-11e8-9760-270140786e56.png)

This issue doesn't exist in chrome for me, and it works as expected.

**Comment by marcosnils** [comment]
Try Ctrl + insert and shift + insert

**Comment by dannyhajj** [comment]
@marcosnils yes thank you that works. I had no idea about such shortcut.

Should I close it this issue, or do I keep it open?

**Comment by marcosnils** [comment]
Let's close it as it has been discussed before

**Comment by yashoon** [comment]
This is there for me in chrome, ctrl_insert or shift + insert in not working

**Comment by tonanuvem** [comment]
Use  CTRL+INSERT for COPY 
Use  SHIFT+INSERT for PASTE

Some times i try to paste on notepad, so I can correct some break line

**Comment by UmamaheshMaxwell** [comment]
> Use CTRL+INSERT for COPY Use SHIFT+INSERT for PASTE
> 
> Some times i try to paste on notepad, so I can correct some break line
Thanks a ton [tonanuvem](https://github.com/tonanuvem) , This worked fro me in Chrome !!!
