### ISSUE TITLE
"Click here to load the website" points to wrong URL

### ISSUE THREAD

**Issue by handre** [play-with-docker/play-with-docker.github.io#126]
On step 7 off "beginner-linux" tutorial, there is this link "Click here to load the website" which supposedly points to the site "created" by the beginner, but instead it loads `"https://training.play-with-docker.com"` which is the home page of PWD  (obviously it works with the docker image running or not).

It's happening because firefox (53.0.2 (64-bit) for Windows7) translates "/" to the mentioned URL.

**Comment by handre** [comment]
Same in chrome for Windows "Version 65.0.3325.181 (oficial version) 64 bits"

**Comment by ManoMarks** [comment]
@marcosnils can you take a look?

**Comment by marcosnils** [comment]
@handre are you trying to open it a new tab or something?. Are you just left clicking on it?. Just tried both i Chrome and Firefox and works from my end. Can you replicate @ManoMarks ?

**Comment by marcosnils** [comment]
@handre even if you see the  "/" in the `href` attribute,  the `onclick` function of that link is replaced by some PWD custom code that should redirect to the proper url. But it only works if you left click on that. "Opening in a new tab" usually has the behaviour you're seeing.

**Comment by ErlendLandro** [comment]
I also found this confusing. I always open stuff in a new tab, so I was just led to https://training.play-with-docker.com. If you hover over the link, that's what you're seeing as well.

**Comment by marcosnils** [comment]
yes. That's correct. It's just that the link gets populated through a javascript function. I guess the best think to do would be to add a notice about left clicking, WDYT?

**Comment by ErlendLandro** [comment]
> I guess the best think to do would be to add a notice about left clicking, WDYT?

If there's no better way to solve this problem so that it behaves like a normal link, I think a note about it is fine.

**Comment by ibnesayeed** [comment]
I have tried to fix it by changing the `href` value of those links on right click in https://github.com/play-with-docker/sdk/pull/16.

**Comment by Deifinger** [comment]
@marcosnils I usually click on links by middle button on mouse for opening in new tab. I found, that we can fix that by adding click handler on "onauxclick" event to actions object: [link to action handler line](https://github.com/play-with-docker/sdk/blob/32dabbe2fd780f150b531224b4b5a1c17fbd18e8/index.js#L64)

If you want I can create pull request for fix this.

**Comment by ibnesayeed** [comment]
@Deifinger there is a PR https://github.com/play-with-docker/sdk/pull/16 already for right click handling which has been waiting for review for over a month now. If that one is tested and merged, other niche possibilities can be explored.

**Comment by marcosnils** [comment]
I'll check the SDK changes today.

**Comment by marcosnils** [comment]
@Deifinger @ibnesayeed thx for the suggestions / contributions. I've just released some changes based on your input that should fix this. Please advise if there's anything you see it's not working.
