### ISSUE TITLE
Acessing MySQL image remotely

### ISSUE THREAD

**Issue by renansouza-dev** [play-with-docker/play-with-docker.github.io#136]
Hi there!

I am uploading a MySQL image and trying to access remotely, but to no avail. Has anyone succeeded in doing the same?

1) docker pull mysql
2) docker run -it --name sql -e MYSQL_DATABASE = sql -e MYSQL_ROOT_PASSWORD = root -p 3306: 3306 or 80 -d mysql

Best regards.

**Comment by renan86** [comment]
Hi there!

I am uploading a MySQL image and trying to access remotely, but to no avail. Has anyone succeeded in doing the same?

1) docker pull mysql
2) docker run -it --name sql -e MYSQL_DATABASE = sql -e MYSQL_ROOT_PASSWORD = root -p 3306: 3306 or 80 -d mysql

Best regards.

**Comment by marcosnils** [comment]
PWD doesn't forward TCP traffic. You have to use something like adminer to
access

sent from mobile
