### ISSUE TITLE
webapps/#231: apk add does not work

### ISSUE THREAD

**Issue by hervenicol** [play-with-docker/play-with-docker.github.io#15]
At [webapps workshop, step 2.3.1](http://birthday.play-with-docker.com/webapps/#231-create-a-python-flask-app-that-displays-random-cat-pix) :

> You will also need a text editor. We recommend vim, which will already be installed in the terminal. However if you wanted, for example, emacs, you would install it using the Alpine package manager:
> 
> apk add emacs
> 

At this point in the workshop, "apk add" won't work as apk has no valid database yet.
I guess `apk add --update emacs` would work better.

**Comment by ManoMarks** [comment]
@marcosnils did you say you were going to install emacs by default? We could remove this if so.

**Comment by ManoMarks** [comment]
Fixed in #28
