### ISSUE TITLE
Very first command in the Docker for Beginners fails

### ISSUE THREAD

**Issue by andrewandante** [play-with-docker/play-with-docker.github.io#152]
Not the greatest look when starting off :)

```bash
[node1] (local) root@192.168.0.63 ~
$     git clone https://github.com/dockersamples/linux_tweet_app
Cloning into 'linux_tweet_app'...
remote: Counting objects: 14, done.
remote: Total 14 (delta 0), reused 0 (delta 0), pack-reused 14
Unpacking objects: 100% (14/14), done.
[node1] (local) root@192.168.0.63 ~
$ docker container run alpine hostname
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```

**Comment by marcosnils** [comment]
Thx for reporting the issue. I believe it's an issue with the docker daemon used in PWD. I'll update it later today.

**Comment by ManoMarks** [comment]
@andrewandante This is you running it locally I guess? Since it works on the site.

**Comment by marcosnils** [comment]
@ManoMarks this wasn't working when I tested it before. Seems like it was a temporary issue with the Alpine image manifest. I'll close as it's working now

**Comment by yosifkit** [comment]
Yeah, we had a build hiccup on `alpine:3.8`: https://github.com/docker-library/official-images/issues/4543#issuecomment-403054847.
