### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by ibnesayeed** [play-with-docker/play-with-docker.github.io#158]
A favicon establishes branding as well as helps quickly find the desired tab when there are dozens of tabs open in a browser window.

**Comment by shrn01** [comment]
Yes, having a favicon would make the website look more good.

**Comment by marcosnils** [comment]
Any suggestions?

**Comment by shrn01** [comment]
We could just use a resized version of the image in play with docker website.

https://www.docker.com/sites/default/files/Whale%20Logo332_5.png

**Comment by marcosnils** [comment]
SGTM! would you like to send a PR to add it?

**Comment by shrn01** [comment]
Yeah cool doing it
