### ISSUE TITLE
webapps#2.1 - no link to open "hello [your name]" container?

### ISSUE THREAD

**Issue by hervenicol** [play-with-docker/play-with-docker.github.io#16]
At [webapp workshop, step 2.1](http://birthday.play-with-docker.com/webapps/#21-run-a-static-website-in-a-container):

> If you were running Docker for Mac, Docker for Windows, or Docker on Linux, you would see your app at http://[YourDockerIP]:32773.

Nice. But when I'm using play-with-docker , I'd also like a link to the container I just started.

**Comment by ManoMarks** [comment]
Yeah the problem we have with this step is that the port is variable. The PWD SDK requires us to specify the port in creating a link. So we can't for this step. But we do in step 2.2

**Comment by marcosnils** [comment]
Right, there's nothing we can do here as for PWD to populate ports, we need to know them beforehand.
