### ISSUE TITLE
TLS certificate issue

### ISSUE THREAD

**Issue by ibnesayeed** [play-with-docker/play-with-docker.github.io#167]
I was trying to test the effect of recent fix of #126. I tried following a tutorial in the PWD that would run a web service which can be opened in a new window. It turns out that the link opens as expected, but there is some TLS certificate issue.

![pwd-tls-error-chrome](https://user-images.githubusercontent.com/65147/47610282-37cfb280-da1f-11e8-87c3-76ce2fe4dab8.png)

![pwd-tls-error-firefox](https://user-images.githubusercontent.com/65147/47610284-37cfb280-da1f-11e8-8d28-fbdc4953f0b2.png)

![pwd-tls-error-curl](https://user-images.githubusercontent.com/65147/47610283-37cfb280-da1f-11e8-8f9b-a79d7c82767b.png)

**Comment by marcosnils** [comment]
Fixed.
