### ISSUE TITLE
docker-volumes workshop: image name inconsistency

### ISSUE THREAD

**Issue by hervenicol** [play-with-docker/play-with-docker.github.io#18]
at [docker-volumes in a Dockerfile](http://birthday.play-with-docker.com/docker-volumes/#defining-a-volume-in-a-dockerfile):

> Let’s build an image from this Dockerfile.
> 
> `docker image build -t img1 .`
> 
> We will then create a container in interactive mode (using -ti flags) from this image and name it c2.
> 
> `docker container run --name c2 -ti img`

There's an inconsistency: the image is named "img1" at build, then we try to create our container from "img".

**Comment by marcosnils** [comment]
@hervenicol would you like to send a PR to fix this?

**Comment by ManoMarks** [comment]
Thanks, fixed!
