### ISSUE TITLE
how is possible to use custom franela/image as mention in pwd repo 

### ISSUE THREAD

**Issue by arenaitmx** [play-with-docker/play-with-docker.github.io#181]
Hi there,

   We want to use specific docker image per "_post" how is this possible, I was reading at pwd repo, and build own franela/images is possible but how to address this at markdown level?

PD: awesome job here we are amazed with the technology, congrats! help in so many ways

Regards

**Comment by marcosnils** [comment]
yes it's possible. Here's an example. https://raw.githubusercontent.com/play-with-docker/play-with-docker.github.io/dd2882a6d42900574a0dc711640e96c01f2dabed/_posts/2017-03-26-multi-stage.markdown

If you change the **image** front it can run other images. Take into account that the image needs to be pulled and available in the environment you're testing. 

Apologies for the delay.
