### ISSUE TITLE
blank commandline window after installation

### ISSUE THREAD

**Issue by chunhualiao** [play-with-docker/play-with-docker.github.io#182]
Hi, I was trying to install my own instance of the training website. I created a Ubuntu 18.04 VM on a cloud, installed docker, cloned this git repo and followed the instructions to start the website. I am able to access http://localhost:4000/ops-s1-images/.  However, the commandline window is always blank, no commandline showing up.  Resizing does not help neither. 

![image](https://user-images.githubusercontent.com/1627206/57823904-0ebe0780-774e-11e9-8dba-9ced89391029.png)

If I use the same Chrome browser to visit the corresponding official page  https://training.play-with-docker.com/ops-s1-images/ , it works fine. 

How to debug this problem? 

The installation guide does not contain info. about the software/hardware requirements so it is not clear if this can be installed on a single VM.

**Comment by marcosnils** [comment]
Please attach the developer console window. 

Thx!.

**Comment by chunhualiao** [comment]
I am totally new. Where to find this console window? Thanks!

**Comment by marcosnils** [comment]
I'm talking about your browser developer console. 

All browsers have a developer console to show how HTTP requests ended up.

**Comment by chunhualiao** [comment]
http://137.135.94.86:4000/ops-s1-hello/ Here is my website.

console view does have some red text:

Failed to load resource: the server responded with a status of 405 ()
(index):1 Access to XMLHttpRequest at 'https://labs.play-with-docker.com/' from origin 'http://137.135.94.86:4000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ouankou** [comment]
I spent some time on this issue and fixed it eventually as follows.

The reason why the right panel is blank is that the request sent to PWD server is blocked by browser due to CORS policy. To run Chrome browser with security checking disabled will solve the issue temporarily.

For a more convenient solution, we need to fix it on the server side. The config file of HAproxy need to be modified.
1. ```<PWD_root_folder>\haproxy\haproxy.cfg```
```bash
...
global
    lua-load /usr/local/etc/haproxy/cors.lua

frontend http-in
    bind *:8080

    acl host_direct hdr_reg(host) -i ^.*\.direct\..*?:?.*$

    use_backend l2 if host_direct

    default_backend pwd 

    # Add CORS headers when Origin header is present
    capture request header origin len 128
    http-response add-header Access-Control-Allow-Origin %[capture.req.hdr(0)] if { capture.req.hdr(0) -m found }
    http-request use-service lua.cors-response if METH_OPTIONS { req.hdr(origin) -m found }
    rspadd Access-Control-Allow-Credentials:\ true  if { capture.req.hdr(0) -m found }
...
```
2. Create a new LUA script ```cors.lua``` along with the config file to handle ```OPTIONS``` method.
```lua
core.register_service("cors-response", "http", function(applet)
    applet:set_status(200)
    applet:add_header("Content-Length", "0")
    applet:add_header("Access-Control-Allow-Headers", "Access-Control-Request-Method, Access-Control-Request-Headers, Authorization, X-Requested-With, Content-Type, Origin, User-Agent, If-Modified-Since, Cache-Control, Accept")
    applet:add_header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
    applet:start_response()
end)
```
Then delete the old haproxy docker container and restart PWD server to see the result.

Please note that ```cors.lua``` is located in the ```<PWD_root_folder>\haproxy```. When the container is created, the folder will be mounted as ```/usr/local/etc/haproxy```. That's the reason why we should use this path in the config file.

**Comment by senolcolak** [comment]
This issue is still a problem, I can't make it working even the parameters did not work for me..

**Comment by chunhualiao** [comment]
@senolcolak I wrote a guide https://github.com/chunhualiao/freeCompilerCamp/wiki/Deploy-Play-With-Dock-on-a-local-Ubuntu-18.04-machine . You may want to take a look to see if it helps. The official installation guide is quite limiting for beginners.

**Comment by senolcolak** [comment]
@chunhualiao Thanks a lot for your reply, your guide is really great, especially the domain definition inside the line 58 is really important (although I found it before) my problem is about the console window is not shown inside the Jekyll page like https://egitim.acikkaynakfikirler.com/ops-s1-hello/ here the console is not shown

**Comment by ouankou** [comment]
@senolcolak I checked your website. It seems that your training website is trying to access https://labs.play-with-docker.com/ to get a sandbox. I'm not sure if that's allowed. You may have to set up your own paly-with-docker server and connect it with the training website properly.
If that's not the issue, according to the browser developer console, the CORS policy is not set correctly for your training website. It can't get anything back from https://labs.play-with-docker.com/.
 
You could update CORS setting in a nicer way from following lines.
https://github.com/play-with-docker/play-with-docker/blob/852c075cca366b1742f70aeff20a7b49afb5d067/handlers/bootstrap.go#L60-L69

![image](https://user-images.githubusercontent.com/1269492/83803605-e4056080-a67a-11ea-90dc-b748832c6c53.png)

**Comment by marcosnils** [comment]
> @senolcolak I checked your website. It seems that your training website is trying to access https://labs.play-with-docker.com/ to get a sandbox. I'm not sure if that's allowed.

Correct. That's not allowed. If you want to run PWD in your own domain, you would have to host it.

**Comment by senolcolak** [comment]
I swithed it to the play-with-docker.com just to see if that would work. Again I put my own labs location which is up via direct access https://labs.acikkaynakfikirler.com
