### ISSUE TITLE
swarm-service-discovery: command "ping" missing in images

### ISSUE THREAD

**Issue by mootari** [play-with-docker/play-with-docker.github.io#187]
In https://training.play-with-docker.com/swarm-service-discovery/ below "Service Discovery" the description reads:

> Let’s pick up one of wordpressdb task running on the manager node and try to reach out to wordpressapp running on the remote worker node as shown below:
>
> ```
> docker exec -it e71 ping wordpressapp
> ```
> This should work successfully and able to ping the wordpressapp as service name.

This step fails with:
```
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"ping\": executable file not found in $PATH": unknown
```
The `ping` command is missing both in `mysql:latest` and `wordpress:latest`.

**Comment by marcosnils** [comment]
It's surely because official images removed that command from it. Wanna send a PR to fix it?

**Comment by mootari** [comment]
Done!

**Comment by marcosnils** [comment]
Thanks for contributing!
