### ISSUE TITLE
Image from previous web errors 

### ISSUE THREAD

**Issue by jlk1980** [play-with-docker/play-with-docker.github.io#200]
![Screenshot_20200202-232440_Firefox](https://user-images.githubusercontent.com/60198838/73628198-9241c080-461d-11ea-8c92-69f9df2777e0.jpg)

**Comment by marcosnils** [comment]
@jlk1980 can you please provide more contexto to this issue? A single screenshot is not enough? 

What browser version and OS are you using, please provide as much info as possible otherwise it's very difficult to help.

**Comment by jlk1980** [comment]
I'm using android 8.0 github app

**Comment by jlk1980** [comment]
I'm trying to fix all errors but I'm still in basics

**Comment by marcosnils** [comment]
Oh.. We don't support mobile browsers for the quiz. If you want to contribute and PR we're welcome to receive any contributions

**Comment by jlk1980** [comment]
Ok I will be able to use windows as soon as I can get to my computer
