### ISSUE TITLE
Copyright date not correct on the footer

### ISSUE THREAD

**Issue by Bam92** [play-with-docker/play-with-docker.github.io#201]
Hi!

The copyright date not correct on the footer is not correct. It is written 2017 - 2019 instead of 2017 - 2020.

**Comment by marcosnils** [comment]
:+1: thx for noticing. Want to open a PR to fix it?

**Comment by Bam92** [comment]
Yes, if you allow me to do so.

**Comment by Privat33r-dev** [comment]
The issue can be closed as currently there is no copyright date in the footer. 

<details><summary>Joke</summary>
True Stalin-style solution. 
<img src=https://github.com/play-with-docker/play-with-docker.github.io/assets/39376984/23f8ba28-9394-43be-8ca1-2d0d66982579>
</details>
