### ISSUE TITLE
tutorial website does not show shell

### ISSUE THREAD

**Issue by TjrGithub** [play-with-docker/play-with-docker.github.io#204]
Hi, I'm trying get the tutorial https://training.play-with-docker.com/microservice-orchestration/   to work. I'm on a fully current Ubuntu 19.10, Firefox 74.0, and a fresh Firefox profile. But there is no "shell" window on the right hand side (despite resizing): https://imgur.com/a/BdOT8eK Does anybody know how to make it appear?

![docker-tutorial-Bildschirmfoto vom 2020-03-23 18-00-39](https://user-images.githubusercontent.com/515569/77343299-c25e3380-6d31-11ea-9b01-dfc3907dde59.png)

**Comment by marcosnils** [comment]
Should be fixed now
