### ISSUE TITLE
Console not showing because of CORS problem,

### ISSUE THREAD

**Issue by victorponz** [play-with-docker/play-with-docker.github.io#215]
Console not showing because of CORS problem,
![image](https://user-images.githubusercontent.com/35145182/104120536-f5f96100-5337-11eb-8b78-27b6c36e803f.png)

**Comment by marcosnils** [comment]
hey @victorponz you need to use `localhost` as the hostname in your browser in order for PWD to run locally. Seems like you're using 0.0.0.0:4000.
