### ISSUE TITLE
POST https://mydomain/ 405 (Method Not Allowed) - causing terminal not to work

### ISSUE THREAD

**Issue by mahdymo** [play-with-docker/play-with-docker.github.io#242]
Hi, 
I'm getting this error starting from last night, and not sure how to overcome it, I found the sdk js fetched initiate the post calls to the play website, yet as I understand jekyll should work with GET calls only. 

if this faced anyone, or any help that would be great

**Comment by marcosnils** [comment]
hi, nothing changed from the PWD side. Can't help without having more information.

**Comment by mahdymo** [comment]
Hi, thanks, sorry will close this issue, it was a wrong nginx destination at my side, causing traffic with POST calls to be directed to Jekyll backend that doesn't accept POST. now it's fixed so POST calls are destined to PWD haproxy server.
