### ISSUE TITLE
Docker for Beginners - Linux: no space left on device

### ISSUE THREAD

**Issue by vollkorn1982** [play-with-docker/play-with-docker.github.io#243]
When doing the beginner training at https://training.play-with-docker.com/beginner-linux/ I receive the following error at the step "Run a background MySQL container":

![grafik](https://github.com/play-with-docker/play-with-docker.github.io/assets/1755585/6f622e06-077b-4780-9e9c-7d78fbd58d99)

Unfortunately, I could not figure out how to copy & paste from the web console.

I would classify this as a bug, because it stops me from advancing in the course.

**Comment by marcosnils** [comment]
Hi, can you refresh the page to start over and try again please?

**Comment by vollkorn1982** [comment]
Works now, thank for the fix.
