### ISSUE TITLE
Service causes abrupt session termination

### ISSUE THREAD

**Issue by Privat33r-dev** [play-with-docker/play-with-docker.github.io#244]
In the at least 3-rd to 5-th steps of the [Application Containerization and Microservice Orchestration](https://training.play-with-docker.com/microservice-orchestration/) tutorial, running provided container causes session to close. In the tutorial environment it looks like this:

<details><summary>Screenshot of abruptly terminated session in web environment</summary>
<p>
<img src="https://github.com/play-with-docker/play-with-docker.github.io/assets/39376984/23b6a759-e841-4382-973d-3c504f36cfc6">
</p>
</details> 

I am not sure what my cause it, but my bet that it's related to some security feature that prevents malicious usage of the test environment.

To make sure that it wasn't a fluke I ran the same thing in the [lab](https://labs.play-with-docker.com/) (using web and ssh interfaces) with the similar result
![image](https://github.com/play-with-docker/play-with-docker.github.io/assets/39376984/06164fb8-b9a7-4dd6-ac7d-947cfe684323)

I tried to change port to `31337` and it didn't seem to help (normally it didn't even publish the app's port since it should've been `31337:5000`). I also tried to limiting the app to the local-only environment by setting IP to 127.0.0.1, but to no avail. 
<details><summary>Screenshot of abruptly terminated session in web environment with port set to 127.0.0.1:31337:31337</summary>
<p>
<img src="https://github.com/play-with-docker/play-with-docker.github.io/assets/39376984/b3916ea3-cee1-47ae-8a35-5c8015d79e80">
</p>
</details>

Another thing that I done is running nginx server. It ran fine for 10-15 minutes, but in a few seconds after starting tutorial service, the session is getting shut down.

The series of further tests has shown that changing container's name does not have any effect.

Changing port of the Flask's application doesn't help as well:
<details><summary>Screenshot of abruptly terminated session with flask running on 31337 port</summary>
<p>
<img src="https://github.com/play-with-docker/play-with-docker.github.io/assets/39376984/6f8d7f71-6e78-4201-ad06-1314eff908fd">
</p>
</details>

Issue might be related to the resource limitation. I ran flask server without the api in the next test.
The `main.py` from step3 is changed to
```py
#!/usr/bin/env python

from flask import Flask
from flask import request
from flask import jsonify
from linkextractor import extract_links

app = Flask(__name__)

@app.route("/")
def index():
    return "Empty app"

app.run(host="0.0.0.0", port="1337")
```

it caused the same issue.

**Comment by marcosnils** [comment]
hey! this should be fixed now!

**Comment by Privat33r-dev** [comment]
> hey! this should be fixed now!

What was the root of the issue, if I may ask? :)

**Comment by marcosnils** [comment]
some internal checks that were triggering a false positive on those labs.
