### ISSUE TITLE
Section 2.1 URL links to training.play-with-docker.com

### ISSUE THREAD

**Issue by ghost** [play-with-docker/play-with-docker.github.io#25]
Even issue #21 is/should be resolved, the link is pointing to the home site of the tutorial.
I then tried with
```
http://pwd10_0_7_3-8888.host3.labs.play-with-docker.com/
```
and got a 'Error forwarding request' message.
However
```
http://pwd10_0_7_3-8888.host2.labs.play-with-docker.com/
```
worked.

It seems that the link should be fixed again or am I doing something wrong?

**Comment by marcosnils** [comment]
hmm works fine for me @devhkr. The link is generated dynamically depending on the PWD host that was assigned to that session, that's why it's not static. @dserodio  did it work for you?

**Comment by ghost** [comment]
Oh, it's suddenly working!
Ah, I got it, I tried to open the link in a new tab which opens the home site. Just direct click redirects me to the proper test site 😄 

Anyway, thanks for your prompt feedback.

**Comment by marcosnils** [comment]
@devhkr sometimes you get the `Error forwarding request` when the container hasn't fully started. Glad it worked!
