### ISSUE TITLE
Tutorial not working without activating experimental features

### ISSUE THREAD

**Issue by MathiasRenner** [play-with-docker/play-with-docker.github.io#26]
[This tutorial](https://github.com/franela/franela.github.io/blob/master/_posts/2017-01-23-swarm-compose-secrets.markdown)  requires using latest Docker Engine 17.04 requires experimental features to be activated:

```
# docker service logs -f SERVICE-ID
only supported on a Docker daemon with experimental features enabled
```

This is not mentioned in the tutorial, but should be. Maybe experimental features shouldn't be used in a tutorial at all.
All other tutorials I've done were great so far, thanks for your work!

**Comment by marcosnils** [comment]
@MathiasRenner thx for the comment, glad you liked the tutorials. I'll add a note into the tutorial about the experimental feature.

**Comment by MathiasRenner** [comment]
@marcosnils Wow, that was fast, thanks :-)
