### ISSUE TITLE
nodejs-live-debugging error

### ISSUE THREAD

**Issue by jplandrain** [play-with-docker/play-with-docker.github.io#31]
It looks like there is an error in the intermediate track Live Debugging Node.js with Docker (nodejs-live-debugging)

The solution given under the title "Fix the bug" (modify the '>' into a '>=' in the conditional) doesn't work because the variable "message" is already evaluated when reaching this line. Therefore, this change has no visible effect in the running application and the empty line is still shown.

**Comment by marcosnils** [comment]
@jplandrain thx for reporting. Would you like to send a PR to fix this?. Change seems simple.

**Comment by jplandrain** [comment]
Sorry. I would have done it if I had time to do it, but currently I'm
over-busy.

**Comment by jplandrain** [comment]
Unfortunately, I won't have time before the birthday. I'm over-busy at the moment. I would have done it directly otherwise.

**Comment by ManoMarks** [comment]
@spara can you look?

**Comment by spara** [comment]
Unable to replicate the issue, tutorial works as described.

**Comment by ManoMarks** [comment]
@jplandrain I'm going to go ahead and close this, but if you have more info for us you can re-open.
