### ISSUE TITLE
We need a common landing page for play-with-{docker,moby,k8s}

### ISSUE THREAD

**Issue by mjbright** [play-with-docker/play-with-docker.github.io#40]
I'd opt to put a link from the play-with-docker.github.io landing page to the moby and k8s projects.

In any case I think it would be good to have one landing page with one easy to remember URL to access the various services
   - PWD => lab, training, github, ...
   - PWM => 
   - PWK =>

**Comment by Wittionary** [comment]
I like the idea. Does the project maintainer own the play-with-containers.com domain? Looks like it was bought on 7-7-17. [Whois](https://www.whois.com/whois/play-with-containers.com)

**Comment by marcosnils** [comment]
Yes, we own play-with-containers also. Ideally we wanted to create a landing with all the projects, but we don't have the bandwidth to do that ATM. :cry:

**Comment by Wittionary** [comment]
@marcosnils As in internet bandwidth/server costs or engineering resources?

**Comment by marcosnils** [comment]
Engineering resources

**Comment by Wittionary** [comment]
If you create the repo for the page and give a list of requirements for an MVP, I should be able to get a barebones version going.

**Comment by marcosnils** [comment]
Sounds like a good plan. I'll create a repo and we can discuss the details there.

**Comment by marcosnils** [comment]
Let's continue the discussion here https://github.com/play-with-docker/play-with-contianers/issues/1
