### ISSUE TITLE
Docker Config Lesson using incorrect Version

### ISSUE THREAD

**Issue by whytoe** [play-with-docker/play-with-docker.github.io#41]
http://training.play-with-docker.com/swarm-config/, on the webpage it says: 

- Requirements: Docker 17.06+

In the Terminal it indicates:
[node1] (local) root@10.0.85.3 ~
$ docker --version
Docker version 17.05.0-ce, build 89658be

**Comment by marcosnils** [comment]
Fixed. Thx for reporting!.
