### ISSUE TITLE
windows-containers-multicontainer - ERROR: Service 'web' failed to build: unknown blob

### ISSUE THREAD

**Issue by emecas** [play-with-docker/play-with-docker.github.io#43]
/windows-containers-multicontainer lab is throwing this error:

ERROR: Service 'web' failed to build: unknown blob

Output:

PS C:\Users\emecas\repos\PERSONAL\Musicstore> docker-compose -f .\docker-compose.windows.yml build
db uses an image, skipping
Building web
Step 1/16 : FROM microsoft/dotnet:1.1-sdk-msbuild-nanoserver
1.1-sdk-msbuild-nanoserver: Pulling from microsoft/dotnet
bce2fbc256ea: Downloading
3ac17e2e6106: Downloading
97751c107417: Download complete
d41346f6829a: Download complete
1bd0bb59ef42: Download complete
6aaad46736cc: Download complete
9f260a2e5ce0: Download complete
1fe9082c1036: Download complete
5303913da151: Download complete
ERROR: Service 'web' failed to build: unknown blob
PS C:\Users\emecas\repos\PERSONAL\Musicstore>

**Comment by marcosnils** [comment]
@sixeyed ^

**Comment by marcosnils** [comment]
@ManoMarks @StefanScherer

**Comment by ManoMarks** [comment]
This is usually a result of using Linux containers instead of Windows containers. @emecas can you verify you are using Windows containers and try again?
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by StefanScherer** [comment]
Yes, switching to Windows containers should solve the problem.

**Comment by marcosnils** [comment]
Thx everyone for getting back so quickly!.
