### ISSUE TITLE
clicking with the mouse on the terminal sends input which causes unexpected behavior

### ISSUE THREAD

**Issue by cglewis** [play-with-docker/play-with-docker.github.io#43]
<img width="810" alt="screen shot 2017-07-18 at 8 57 10 pm" src="https://user-images.githubusercontent.com/2931079/28350145-ba8b2346-6bfb-11e7-912c-4de5036c384f.png">

this doesn't seem to be an issue on PWD, but only on this site using PWD.

**Comment by marcosnils** [comment]
thanks for reporting. This doesn't happen to me. You're clicking with the left button right?. Additionally, which browser and version are you using?

Thx!.

**Comment by cglewis** [comment]
Yes, left click.  OSX, Google Chrome Version 59.0.3071.115 (Official Build) (64-bit).
git commit c52c68b418d4a1e18d19a2053432bc1e03bdb7f4

**Comment by marcosnils** [comment]
Have you tried if it happens in safari also?.

**Comment by cglewis** [comment]
Apologies, this error is a symptom of something else.  Same issue in safari, but found that it's a result of using ncurses.  For some reason when running a program that uses ncurses, clicking causes a seg fault, and then after that subsequent clicks in the terminal produce the above behavior.  Without using ncurses the clicking in terminal behavior does not happen in Chrome or Safari for me.

Not sure if this problem is out of scope for this project?  Means I cause make tutorials that use ncurses though.  Could be a problem with alpine.

**Comment by cglewis** [comment]
Also am able to reproduce on PWD, so appears to be related to either the TERM settings or alpine seg faulting on ncurses.  Feel free to close this if you think it's out of scope.

**Comment by marcosnils** [comment]
thx for sharing the results. Which ncursos program are you testing with?

**Comment by cglewis** [comment]
it's actually using `npyscreen` which uses ncurses under that.  if you want to try to reproduce:
```
pip install vent
vent
CTRL-X
*click outside of the menu that popped up*
<should seg fault>
<any subsequent left clicks will generate the above>
CTRL-L (to clean up the screen)
```

**Comment by cglewis** [comment]
verified this is an `alpine` issue.  closing.

**Comment by marcosnils** [comment]
:clap: thx for checking!
