### ISSUE TITLE
Duplicate link + 404 

### ISSUE THREAD

**Issue by vcoisne** [play-with-docker/play-with-docker.github.io#53]
On http://training.play-with-docker.com/dev-stage1/

Deploying a Multi-Service App in Docker Swarm Mode is listed twice and link (http://training.play-with-docker.com/dev-stage1/swarm-stack-intro) is 404

**Comment by marcosnils** [comment]
@vcoisne can you please confirm this is fixed?

**Comment by ericat** [comment]
It looks fixed ^__^
