### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by jonocodes** [play-with-docker/play-with-docker.github.io#57]
I'm using FF 55 in Linux. When I try a tutorial it says "try to resize window", but I cannot grab the middle bar to movie it. Also resizing the browser window does nothing.
The capcha never shows.
Chrome works fine.

**Comment by marcosnils** [comment]
@jonocodes works fine for me in FF 55. Do you see any errors in the developer console or something?

![image](https://user-images.githubusercontent.com/1578458/29989175-ca3ff57c-8f47-11e7-9c7f-55962ee47d5d.png)

**Comment by marcosnils** [comment]
Just checked in MacOS and also works.  I'll go ahead and close this issue.

If you're still having issues, please check your developer console logs to see if you get an error there. 

![image](https://user-images.githubusercontent.com/1578458/29989532-02910a7c-8f4a-11e7-9e39-212a5b01285f.png)

**Comment by jonocodes** [comment]
No errors in the console.
Sorry. It appears Privacy Badger was blocking some google stuff which must have prevented the captcha. Working now.

**Comment by marcosnils** [comment]
:thumbsup:
