### ISSUE TITLE
Render offsite tutorials from external Markdown

### ISSUE THREAD

**Issue by jonocodes** [play-with-docker/play-with-docker.github.io#60]
Not sure which repo to file this one under...

I would like a way to showcase my personal project hosted on github by using PWD.

For example I would like the split screen with 2 terminals on the right like this http://training.play-with-docker.com/swarm-mode-intro/.

Right now, I think there are 2 options for me to do this.

1. Use the JS SDK and figure out all the split screen HTML/CSS myself. Then host the HTML myself somewhere and point my users to it.

2. Create a markdown readme using [the tutorial instructions](https://github.com/play-with-docker/play-with-docker.github.io/blob/master/writing-tutorials.md), render it locally with Jekyll to HTML, and then pull out that HTML file and host it somewhere.

Both of these are not ideal because I have to customize and host the HTML myself.

A nice solution would be for me to host a markdown readme in my github repo from step 2 and have PWD render it with Jekyll on the fly and make it usable to users.

Perhaps something like this
http://training.play-with-docker.com/?tutorial=https://raw.githubusercontent.com/jonocodes/samplerepo/develop/pwd_tutorial.md

**Comment by marcosnils** [comment]
Why not forking the training site and make changes as needed? https://github.com/play-with-docker/play-with-docker.github.io.

**Comment by jonocodes** [comment]
@marcosnils that is exactly what I am doing in option 2 above which is not ideal.
Sorry. I could have worded the question better.

**Comment by marcosnils** [comment]
@jonocodes I still don't understand what you want to do. You want your content to appear on the training site but serve it externally?. I think that's not possible because all the content should be licensed according to the `contributor` guide (https://github.com/play-with-docker/play-with-docker.github.io/blob/master/contribute.md). So we can't really display external content that doesn't follow the contributing guides.

**Comment by jonocodes** [comment]
Yes. I want to create a tutorial that I host but is rendered from an external site. That site can be training.play-with-docker.com or renderer.play-with-docker.com or some-external-pwd-renderer.com

I dont want it hosted on training.play-with-docker.com because its not a general docker tutorial. Its an external project. This can be useful for many projects that dont belong on the PWD site itself. Any web app, any database, any personal project.

Forking the repo is a lot of overhead and hard to upkeep and maintain for someone that wants to just show a single tutorial. They also need to manage hosting it. It would be simpler for me to version control a single readme in my git repo instead for forking all the tutorials for every one of my projects.

I believe now there is a way to pass PWD a stack file (though I have not been able to find the documentation for it) and it will start by bringing up that stack. I know this is out of the scope of the tutorials section, but this is a little closer to what I'm talking about. Instead of feeding it a stack, feed it an entire tutorial.

Please let me know if you have other ideas of how to make this easy for users.

I would entertain bringing up some sort of third party rendering site if anyone wants to help talk me through this, or if you know anyone else I can discuss this with.

**Comment by marcosnils** [comment]
> Forking the repo is a lot of overhead and hard to upkeep and maintain for someone that wants to just show a single tutorial. They also need to manage hosting it. It would be simpler for me to version control a single readme in my git repo instead for forking all the tutorials for every one of my projects.

I don't think this is the case. Actually forking the repo would be the best option because if upstream receives any updates you can just merge them right away. Regarding hosting, everything's done by github pages, that's where the current training.play-with-docker.com site is being served. You just need to push markdown to your repo and GH pages / Jekyll takes care of the rest.

GH pages is free of charge and extremely easy to setup

**Comment by jonocodes** [comment]
Perhaps I misunderstand. I am currently running Jekyll locally and then saving the output HTML into my repo and hosting that in github pages.

You are saying I should just have github render the Jekyll pages itself. Thats fine. But I would still have to fork the repo. So since I need to keep track of how my fork diverges from upstream, how do I manage this fork? Would I include it as a subtree or something in my repo? And then I am passing around all the other tutorials which I dont need but I suppose I can delete those in my fork or I can just point my users directly to my tutorial page and hope they dont navigate up to the other ones.

**Comment by marcosnils** [comment]
> You are saying I should just have github render the Jekyll pages itself. Thats fine.

Yes. GH pages takes care of that automatically.



> ut I would still have to fork the repo. So since I need to keep track of how my fork diverges from upstream, how do I manage this fork? Would I include it as a subtree or something in my repo? And then I am passing around all the other tutorials which I dont need but I suppose I can delete those in my fork or I can just point my users directly to my tutorial page and hope they dont navigate up to the other ones.

For this repo, remove the tutorials, add your content, change the layout as you prefer and that's it. 
You'll have to keep track of upstream changes of course, but only for the stuff that you think it's relevante to your site. 

It's still not clear to me what your original suggestions was. You wanted to extend this site so it can render external content?. The problem for that is that if we allow it, then anyone would be able to render their content in the official training site which is not what we want.

**Comment by jonocodes** [comment]
You dont need to extend the current site if the current guidelines dont allow it. There can be another site that does this. Lets call it www.pwd-renderer.com

That will take my markdown, render it to HTML (perhaps from javascript even) and display a tutorial. The URL would be something like this:
http://www.pwd-renderer.com/?tutorial=https://raw.githubusercontent.com/jonocodes/samplerepo/develop/pwd_tutorial.md

And it would display a split screen demo of the samplerepo app.

Or perhaps if this is all done from javascript I can just include the JS in my readme somehow. Sort of like how strapdown.js does this. Then I can write a readme and source in www.pwd-renderer.com/render.js

Then when the user instead visits http://rawgit.com/jonocodes/samplerepo/develop/pwd_tutorial.md, they see the same tutorial.

For example view the source of this page http://rawgit.com/Naereen/StrapDown.js/master/example2.html

**Comment by marcosnils** [comment]
@jonocodes I see what you're saying. Yes, that' be a good idea. We don't have the bandwidth to create a new site for such purpose now :(. If you want to go ahead and give it a try we can try to help in what we can.

**Comment by jonocodes** [comment]
ok. Bandwidth issue here too. But if I get the chance to implement where should I go to ask PWD questions about this sort of thing?

**Comment by marcosnils** [comment]
@jonocodes we're in the docker community slack dockercommunity.slack.com in the #play-with-docker channel.

**Comment by jonocodes** [comment]
FYI, here is my solution
https://github.com/jonocodes/pwder/
and here is a demo
http://pwder.io/?doc=https://raw.githubusercontent.com/jonocodes/pwder/master/hello-example.md
or
http://pwder.io/?doc=https://raw.githubusercontent.com/play-with-docker/play-with-docker.github.io/master/_posts/2017-02-22-go-docker.markdown

let me know what you think

**Comment by marcosnils** [comment]
@jonocodes this is very powerful, thx a lot for the contribution!. We have a lot of ideas of cool things that we can do with this, we'll definitely try to contribute whenever we have some time!.
