### ISSUE TITLE
Command-prompt lagging in web-console

### ISSUE THREAD

**Issue by neomatrix369** [play-with-docker/play-with-docker.github.io#65]
When a new section in the tutorial is opened, the CLI in the Web console does not open immediately with the prompt available at the cursor - some keys needed to be pressed before the command-prompt would appear.

This is also the case when a page is refreshed (Reload button in the browser).

**Comment by marcosnils** [comment]
We're aware of this issue and we're working on it in the official PWD repo. I'll close here as it's not related to the bday site. Thx for reporting!.

**Comment by neomatrix369** [comment]
@marcosnils is there an existing PR or branch or issue we can link this to, thanks for reviewing and actioning on it
