### ISSUE TITLE
No means to open the second tab in the tutorial window

### ISSUE THREAD

**Issue by neomatrix369** [play-with-docker/play-with-docker.github.io#66]
There is no way to open the second tab as expected (in the instructions) in the tutorial window, on http://birthday.play-with-docker.com/webapps/, see text "Open another terminal window and execute the following commands:...".

Note: the instruction comes from the time when we it was applicable on our local machine environment.

**Comment by marcosnils** [comment]
@neomatrix369 labs should still be applicable to local environment and not PWD only. I think this should be kept as is. @ManoMarks ?

**Comment by neomatrix369** [comment]
@marcosnils - thanks for responding, once confirmed, please assign the task to me I'll fix it

**Comment by neomatrix369** [comment]
Sort of related to #35

**Comment by ManoMarks** [comment]
Fixed in #72
