### ISSUE TITLE
Call To Action?

### ISSUE THREAD

**Issue by j0hnst0n** [play-with-docker/play-with-docker.github.io#67]
@ManoMarks as far as the user's next steps after they complete the PWD training, what would be most useful for us to recommend, eg, "Download Docker for Mac/Windows" or "Create a Docker ID" or something else?
![image](https://user-images.githubusercontent.com/1610391/32062936-caa9eff0-ba2a-11e7-8fc6-81fdb45adab7.png)

**Comment by ManoMarks** [comment]
Good call fixed in #68
