### ISSUE TITLE
Getting 500 error on login page

### ISSUE THREAD

**Issue by j0hnst0n** [play-with-docker/play-with-docker.github.io#73]
@ManoMarks from this page ...
![image](https://user-images.githubusercontent.com/1610391/32442803-867cc6ec-c2b1-11e7-9855-a2b613f4c52c.png)

... am getting this error after 3-4 minutes
![image](https://user-images.githubusercontent.com/1610391/32442828-995e7904-c2b1-11e7-8757-c0fddeb61ee3.png)

**Comment by j0hnst0n** [comment]
@ManoMarks same experience here, assume it's the same / similar issue
![image](https://user-images.githubusercontent.com/1610391/32442913-f34b967c-c2b1-11e7-9354-a99bf6024a40.png)

**Comment by marcosnils** [comment]
Fixed!
