### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by mneverov** [play-with-docker/play-with-docker.github.io#75]
It states in networking lab (Step 4: Test the network) that after we ran two services and ping one from another there is 100% packet loss. The output of ping command is shown after words "Now, lets ping 10.0.0.3.".
I believe the output should be opposite, something like "5 packets transmitted, 5 received, 0% packet loss, time 3997ms".

At the end of the same lab swarm exit command printed twice:

> Lets run docker swarm leave --force.
> docker swarm leave --force
> Lets also run docker swarm leave --force.
> docker swarm leave --force

Security Lab Capabilities contains 404 link in a sentense:
> By default, Docker drops all capabilities except those [needed](https://github.com/moby/moby/blob/master/oci/defaults_linux.go#L64-L79), using a whitelist approach.

**Comment by ibnesayeed** [comment]
> At the end of the same lab swarm exit command printed twice:

I think this is because there are two terminals and both need to be killed.

**Comment by marcosnils** [comment]
> The output of ping command is shown after words "Now, lets ping 10.0.0.3.".
> I believe the output should be opposite, something like "5 packets transmitted, 5 received, 0% packet loss, time 3997ms".

This is because the ip of the containers changed and it's not `10.0.0.3` anymore and it's in the form of `192.168.x.x`. @max-neverov would you like to submit a PR to fix it?

**Comment by marcosnils** [comment]
> At the end of the same lab swarm exit command printed twice:

That's correct because you need to exist the shell in both terminals.

**Comment by marcosnils** [comment]
> Security Lab Capabilities contains 404 link in a sentense:

just checked this and it works.

**Comment by mneverov** [comment]
@marcosnils just checked the [link](https://imgur.com/a/Bk86y8R) and got 404 again.

**Comment by marcosnils** [comment]
@max-neverov the link you've provided it's not the one that's currently in the training site. This is what's there now (https://github.com/moby/moby/blob/5f17312653c3e4dc5474f86692b09f06262a1ebd/oci/defaults.go#L14-L31) which works. Can you please verify?

**Comment by mneverov** [comment]
Yes, it works.
