### ISSUE TITLE
Docker swarm config files - command line does not appear

### ISSUE THREAD

**Issue by darius-v** [play-with-docker/play-with-docker.github.io#93]
Only shows message "If the commandline doesn't appear in the terminal, make sure popups are enabled or try resizing the browser window."

Tried resizing window. Probably popups are enabled because command line works in other tutorial pages.

**Comment by marcosnils** [comment]
Have you tried refreshing the page? It should work

**Comment by darius-v** [comment]
Just loaded it again, it does not work. http://training.play-with-docker.com/swarm-config/

I see suspitious thing. In network I see there post done to this https://hybrid.play-with-docker.com/sessions/b95mlri62ceg008me2sg/instances

but it returns 500 error.

**Comment by marcosnils** [comment]
Fixed!.
