### ISSUE TITLE
Opening linux_tweet_app in new tab (middle-mouse) opens training.play-with-docker.com

### ISSUE THREAD

**Issue by rgeraads** [play-with-docker/play-with-docker.github.io#94]
I was afraid that opening the link in the tutorial would navigate the browser away from the current page, so I used the middle mouse button to open it in a new tab, but that doesn't show the desired result.

Normal click does show it correctly.

https://github.com/play-with-docker/play-with-docker.github.io/blob/0454a13ce444cde5423f1f84523e03785a2af38c/_posts/2016-10-25-beginner-linux.markdown#L436

**Comment by marcosnils** [comment]
yes, that's the way it works. Because we're adding handlers dynamically to the links, middle click doesn't work.
